// Autogenerated using mud system-types
import ActionSystem from "../abi/ActionSystem.json";
import CommitSystem from "../abi/CommitSystem.json";
import ComponentDevSystem from "../abi/ComponentDevSystem.json";
import InitSystem from "../abi/InitSystem.json";
import MoveSystem from "../abi/MoveSystem.json";
import PlayerSpawnSystem from "../abi/PlayerSpawnSystem.json";
import ShipSpawnSystem from "../abi/ShipSpawnSystem.json";

export const SystemAbis = {
  "ds.system.Action": ActionSystem.abi,
  "ds.system.Commit": CommitSystem.abi,
  "ds.system.ComponentDev": ComponentDevSystem.abi,
  "ds.system.Init": InitSystem.abi,
  "ds.system.Move": MoveSystem.abi,
  "ds.system.PlayerSpawn": PlayerSpawnSystem.abi,
  "ds.system.ShipSpawn": ShipSpawnSystem.abi,
};
