// Autogenerated using mud system-types
import { ActionSystem } from "./ethers-contracts/ActionSystem";
import { CommitSystem } from "./ethers-contracts/CommitSystem";
import { ComponentDevSystem } from "./ethers-contracts/ComponentDevSystem";
import { InitSystem } from "./ethers-contracts/InitSystem";
import { MoveSystem } from "./ethers-contracts/MoveSystem";
import { PlayerSpawnSystem } from "./ethers-contracts/PlayerSpawnSystem";
import { ShipSpawnSystem } from "./ethers-contracts/ShipSpawnSystem";

export type SystemTypes = {
  "ds.system.Action": ActionSystem;
  "ds.system.Commit": CommitSystem;
  "ds.system.ComponentDev": ComponentDevSystem;
  "ds.system.Init": InitSystem;
  "ds.system.Move": MoveSystem;
  "ds.system.PlayerSpawn": PlayerSpawnSystem;
  "ds.system.ShipSpawn": ShipSpawnSystem;
};
