// Autogenerated using mud system-types
export const systemToId = {
  ActionSystem: "ds.system.Action",
  CommitSystem: "ds.system.Commit",
  ComponentDevSystem: "ds.system.ComponentDev",
  InitSystem: "ds.system.Init",
  MoveSystem: "ds.system.Move",
  PlayerSpawnSystem: "ds.system.PlayerSpawn",
  ShipSpawnSystem: "ds.system.ShipSpawn",
};

export const idToSystem = {
  "ds.system.Action": "ActionSystem",
  "ds.system.Commit": "CommitSystem",
  "ds.system.ComponentDev": "ComponentDevSystem",
  "ds.system.Init": "InitSystem",
  "ds.system.Move": "MoveSystem",
  "ds.system.PlayerSpawn": "PlayerSpawnSystem",
  "ds.system.ShipSpawn": "ShipSpawnSystem",
};
